sp500 = ['AAPL', 'MSFT', 'NVDA', 'GOOG', 'AMZN', 'GOOGL', 'META', 'TSLA', 'AVGO', 
        'BRK.B', 'WMT', 'JPM', 'LLY', 'V', 'MA', 'UNH', 'ORCL', 'XOM', 'COST', 
        'NFLX', 'HD', 'PG', 'JNJ', 'BAC', 'CRM', 'ABBV', 'KO', 'CVX', 'TMUS', 'WFC',
        'MRK', 'CSCO', 'ACN', 'IBM', 'TMO', 'AXP', 'MS', 'ABT', 'GE', 'GS', 'BX', 
        'LIN', 'NOW', 'PEP', 'MCD', 'DIS', 'ISRG', 'PM', 'QCOM', 'ADBE', 'AMD', 
        'PLTR', 'CAT', 'RTX', 'T', 'INTU', 'TXN', 'BLK', 'VZ', 'SPGI', 'DHR', 
        'BKNG', 'AMGN', 'C', 'SCHW', 'BSX', 'PFE', 'UNP', 'SYK', 'KKR', 'NEE', 
        'LOW', 'AMAT', 'HON', 'ANET', 'PGR', 'UBER', 'TJX', 'BA', 'DE', 'ETN', 
        'CMCSA', 'COP', 'ADP', 'FI', 'SBUX', 'GILD', 'PANW', 'BMY', 'VRTX', 'MDT', 
        'NKE', 'PLD', 'LMT', 'CB', 'MMC', 'ADI', 'LRCX', 'GEV', 'MU', 'KLAC', 'CRWD',
        'UPS', 'APO', 'CEG', 'SO', 'ELV', 'ICE', 'PH', 'MCO', 'SHW', 'PYPL', 'MO', 
        'WM', 'EQIX', 'DUK', 'AMT', 'APH', 'CME', 'WELL', 'INTC', 'HCA', 'MMM', 
        'ABNB', 'CI', 'TT', 'CDNS', 'SNPS', 'CTAS', 'MAR', 'AON', 'CMG', 'PNC', 
        'MSI', 'COF', 'MDLZ', 'FTNT', 'ZTS', 'ITW', 'TDG', 'MCK', 'AJG', 'ORLY', 
        'APD', 'USB', 'EMR', 'REGN', 'DELL', 'BDX', 'RCL', 'CVS', 'ECL', 'CL', 'NOC', 
        'EOG', 'WDAY', 'GD', 'RSG', 'WMB', 'ADSK', 'SPG', 'FDX', 'CSX', 'TGT', 'TFC', 
        'HLT', 'ROP', 'BK', 'KMI', 'MET', 'AFL', 'CARR', 'PCAR', 'NSC', 'VST', 'OKE', 
        'SLB', 'AZO', 'CPRT', 'TRV', 'DLR', 'CHTR', 'PAYX', 'NXPI', 'SRE', 'PSA', 
        'AEP', 'AMP', 'GWW', 'FCX', 'JCI', 'HWM', 'ALL', 'DFS', 'LULU', 'AXON', 
        'ROST', 'URI', 'COR', 'GM', 'CMI', 'PSX', 'NEM', 'FANG', 'O', 'MNST', 'NDAQ', 
        'MPC', 'D', 'MSCI', 'AIG', 'FICO', 'BKR', 'PWR', 'CTVA', 'DHI', 'KR', 'TEL', 
        'FIS', 'OXY', 'KDP', 'CBRE', 'A', 'DAL', 'KMB', 'PRU', 'TRGP', 'EW', 'HES', 
        'AME', 'GLW', 'VLO', 'FAST', 'IT', 'PEG', 'GRMN', 'CTSH', 'KVUE', 'VRSK', 
        'GEHC', 'LHX', 'EXC', 'F', 'ODFL', 'CCI', 'XEL', 'OTIS', 'IR', 'IQV', 'YUM', 
        'CCL', 'VMC', 'KHC', 'WAB', 'SYY', 'HUM', 'ACGL', 'LEN', 'UAL', 'ETR', 'RMD', 
        'IDXX', 'RJF', 'PCG', 'EFX', 'DXCM', 'EXR', 'LYV', 'MTB', 'MLM', 'LVS', 
        'GIS', 'WTW', 'STZ', 'TTWO', 'ED', 'CNC', 'EBAY', 'EA', 'DD', 'HIG', 'ROK', 
        'AVB', 'CSGP', 'WEC', 'VICI', 'MPWR', 'KEYS', 'ANSS', 'EQT', 'HPQ', 'HSY', 
        'NUE', 'XYL', 'EL', 'BRO', 'CAH', 'GDDY', 'IRM', 'TPL', 'FITB', 'STT', 'IP', 
        'MCHP', 'TSCO', 'MTD', 'GPN', 'FTV', 'K', 'DOV', 'HPE', 'BR', 'EQR', 'SW', 
        'DOW', 'DECK', 'SYF', 'PPG', 'CDW', 'CPAY', 'TROW', 'CHD', 'TYL', 'WBD', 
        'VLTO', 'VTR', 'AEE', 'HBAN', 'DTE', 'NTAP', 'PPL', 'WST', 'WAT', 'LYB', 
        'ADM', 'AWK', 'NVR', 'ROL', 'TDY', 'FOXA', 'PHM', 'PTC', 'FE', 'DRI', 
        'HAL', 'FOX', 'HUBB', 'WDC', 'DVN', 'RF', 'WRB', 'ON', 'IFF', 'WY', 
        'ATO', 'NTRS', 'EXPE', 'ZBH', 'STE', 'CINF', 'CBOE', 'SBAC', 'CNP', 
        'ES', 'LII', 'ERIE', 'BIIB', 'CFG', 'EIX', 'LH', 'NRG', 'MKC', 'VRSN', 
        'CTRA', 'STX', 'ZBRA', 'TSN', 'KEY', 'CMS', 'CLX', 'PODD', 'STLD', 'COO', 
        'BLDR', 'INVH', 'ULTA', 'PKG', 'ESS', 'LDOS', 'PFG', 'TER', 'SNA', 'L', 
        'TRMB', 'LUV', 'BBY', 'MAA', 'DGX', 'FDS', 'FSLR', 'JBL', 'MOH', 'NI', 'J', 
        'FFIV', 'JBHT', 'PNR', 'MAS', 'OMC', 'IEX', 'ARE', 'TPR', 'SMCI', 'NWS', 
        'BAX', 'BALL', 'GEN', 'HRL', 'ALGN', 'HOLX', 'GPC', 'CF', 'NWSA', 'EXPD', 
        'DLTR', 'DG', 'BF.B', 'UDR', 'DPZ', 'RL', 'RVTY', 'MRNA', 'KIM', 'LNT', 
        'AKAM', 'EG', 'AVY', 'EVRG', 'DOC', 'APTV', 'DVA', 'EPAM', 'INCY', 'SWKS', 
        'TXT', 'AMCR', 'SWK', 'VTRS', 'KMX', 'POOL', 'REG', 'BXP', 'SOLV', 'JKHY', 
        'NDSN', 'NCLH', 'UHS', 'CAG', 'CPT', 'CHRW', 'TECH', 'HST', 'BEN', 'PAYC', 
        'CPB', 'JNPR', 'ALLE', 'EMN', 'SJM', 'TAP', 'DAY', 'AIZ', 'IPG', 'BG', 'MGM', 
        'GL', 'HSIC', 'ALB', 'PNW', 'AOS', 'LKQ', 'WYNN', 'FRT', 'MTCH', 'GNRC', 'WBA', 
        'MOS', 'IVZ', 'LW', 'CRL', 'ENPH', 'TFX', 'MKTX', 'APA', 'HAS', 'AES', 'CE', 
        'MHK', 'HII', 'CZR', 'PARA', 'BWA', 'FMC']